# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6684071318b3bcaaf7d657a5f631727a34172744aeb5e39eb533d18958b38a465c4b25791917d564dfd34745ba5471b59af66f58061369e0e0e1b3dae16568e6

test:
  secret_key_base: bc356aa6b8c90f64b9d72a2e6f3343f25623efc17cf0c3f3b9737aeb1e4330897db4cc6604e7c0b153dc50b47ba073f97341d672b9a34e50eb36880aa663c111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
